version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/rivet"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/rivet/src/rivet_duckdb"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/rivet/src/rivet_postgres"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/rivet/src/rivet_polars"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/rivet/src/rivet_pyspark"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/rivet/src/rivet_databricks"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/rivet/src/rivet_aws"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
